// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetConversationHistoryApiBackendChatConversationsConversationIdPostResponse,
  GetChatSessionApiBackendChatSessionsChatIdPostResponse,
  GetIndexedRepositoriesApiIndexedReposPostResponse,
  SaveUserApiKeyApiBackendChatKeysSavePostResponse,
} from './types.gen';

const messageResponseSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

const conversationHistoryResponseSchemaResponseTransformer = (data: any) => {
  data.messages = data.messages.map((item: any) => {
    return messageResponseSchemaResponseTransformer(item);
  });
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getConversationHistoryApiBackendChatConversationsConversationIdPostResponseTransformer =
  async (
    data: any,
  ): Promise<GetConversationHistoryApiBackendChatConversationsConversationIdPostResponse> => {
    data = conversationHistoryResponseSchemaResponseTransformer(data);
    return data;
  };

const chatSessionResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  if (data.recent_conversations) {
    data.recent_conversations = data.recent_conversations.map((item: any) => {
      return conversationHistoryResponseSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const getChatSessionApiBackendChatSessionsChatIdPostResponseTransformer = async (
  data: any,
): Promise<GetChatSessionApiBackendChatSessionsChatIdPostResponse> => {
  data = chatSessionResponseSchemaResponseTransformer(data);
  return data;
};

const indexedRepositorySchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const indexedRepositoriesResponseSchemaResponseTransformer = (data: any) => {
  data.repositories = data.repositories.map((item: any) => {
    return indexedRepositorySchemaResponseTransformer(item);
  });
  return data;
};

export const getIndexedRepositoriesApiIndexedReposPostResponseTransformer = async (
  data: any,
): Promise<GetIndexedRepositoriesApiIndexedReposPostResponse> => {
  data = indexedRepositoriesResponseSchemaResponseTransformer(data);
  return data;
};

const apiKeyResponseSchemaResponseTransformer = (data: any) => {
  if (data.created_at) {
    data.created_at = new Date(data.created_at);
  }
  return data;
};

export const saveUserApiKeyApiBackendChatKeysSavePostResponseTransformer = async (
  data: any,
): Promise<SaveUserApiKeyApiBackendChatKeysSavePostResponse> => {
  data = apiKeyResponseSchemaResponseTransformer(data);
  return data;
};
